In [1]:
import pandas as pd
import numpy as np
from sklearn import datasets, linear_model
from sklearn.model_selection import train_test_split
from matplotlib import pyplot as plt
from sklearn.model_selection import LeaveOneOut 


X = np.array([[1, 2], [3, 4]])
y = np.array([1, 2])
loo = LeaveOneOut()


loo.get_n_splits(X)

2

In [14]:
columns = 'age sex bmi map tc ldl hdl tch ltg glu'.split() # Declare the columns names
diabetes = datasets.load_diabetes() # Call the diabetes dataset from sklearn
df = pd.DataFrame(diabetes.data, columns=columns) # load the dataset as a pandas data frame
y = diabetes.target # define the target variable (dependent variable) as y

In [20]:
df.shape

(442, 10)

In [2]:
for train_index, test_index in loo.split(X):
   print("TRAIN:", train_index, "TEST:", test_index)
   X_train, X_test = X[train_index], X[test_index]
   y_train, y_test = y[train_index], y[test_index]
   print(X_train, X_test, y_train, y_test)

TRAIN: [1] TEST: [0]
[[3 4]] [[1 2]] [2] [1]
TRAIN: [0] TEST: [1]
[[1 2]] [[3 4]] [1] [2]


In [4]:
from sklearn.model_selection import cross_val_score, cross_val_predict
from sklearn import metrics

In [8]:
scores = cross_val_score(model, df, y, cv=6)
print('Cross-validated scores:', scores)

NameError: name 'model' is not defined

In [9]:
a = np.arange(8).reshape(2,4) 

In [3]:
a

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [4]:
a.ravel()

array([0, 1, 2, 3, 4, 5, 6, 7])

In [6]:
a.flatten()

array([0, 1, 2, 3, 4, 5, 6, 7])

In [7]:
a

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [ ]:
X_train_8020, X_test_8020, y_train_8020, y_test_8020 = model_selection.train_test_split(estimator, predictor, test_size=0.80, random_state=24601)
y_train_8020 = y_train_8020.as_matrix(); y_test_8020 = y_test_8020.as_matrix();
X_train_8020 = X_train_8020.as_matrix(); X_test_8020 = X_test_8020.as_matrix();

rf_8020 =  RandomForestRegressor(n_estimators = 50,
                                     bootstrap = False,
                                     max_depth = None,
                                     max_features = 4,
                                     min_samples_leaf = 1,
                                     min_samples_split = 4,
                                     random_state = 24601)

results_8020 = rf_8020.fit(X_train_8020, y_train_8020.ravel())
cv_score_8020 = model_selection.cross_val_score(rf_8020, X_train_8020, y_train_8020.ravel(), cv = loocv, scoring = 'neg_mean_squared_error')
print('Default model CV mean:', -cv_score_8020.mean())
print('Default model CV varience:', cv_score_8020.var())

In [ ]:
rf_predict_8020 = rf_optimized.predict(X_test_8020)
rf_train_8020 = rf_optimized.predict(X_train_8020)


train_sizes_8020, train_scores_8020, test_scores_8020 = model_selection.learning_curve(estimator = rf_8020, 
                                                        X = X_train_8020, 
                                                        y = y_train_8020.ravel(),
                                                        scoring='neg_mean_squared_error',
                                                        random_state = 24601,
                                                        cv = loocv,
                                                        train_sizes= [ 4, 8, 12, 16, 20, 24]
                                                        )


plt.style.use('seaborn')

# Training set scores
train_mean_8020 = -np.mean(train_scores_8020, axis=1)
train_std_8020 = np.std(train_scores_8020, axis=1)

# Test set scores
test_mean_8020 = -np.mean(test_scores_8020, axis=1)
test_std_8020 = np.std(test_scores_8020, axis=1)

# Draw lines
plt.plot(train_sizes_8020, train_mean_8020, '--', color='b',  label="Training score")
plt.plot(train_sizes_8020, test_mean_8020, color="r", label="Cross-validation score")

# Draw bands
plt.fill_between(train_sizes_8020, train_mean_8020 - train_std, train_mean_8020 + train_std_8020, color="b",alpha = 0.5)
plt.fill_between(train_sizes_8020, test_mean_8020 - test_std, test_mean_8020 + test_std_8020, color="r", alpha = 0.1)

# Create plot
plt.title("Learning Curve of Random Forest Regression Model", Fontsize = 21)
plt.xlabel("Training Set Size", fontsize = 20), plt.ylabel("MSE", fontsize = 23)
plt.legend(loc="best", fontsize = 22)
plt.tight_layout()
plt.show()